image: 
  file: .gitpod.Dockerfile

tasks:
  - name: Project build (cache) and run instructions
    init: cargo build
    command: |
      # Await for meilisearch to be fully up
      printf 'info: %s' "Awaiting for meilisearch to be fully up"
      until curl --silent --show-error --fail http://localhost:7700/health >/dev/null 2>&1; do sleep 0.5; done

      # Restore config if exists and run bot
      config_name="BotConfig.toml"

      if test -n "${DISCORD_BOT_CONFIG_ENCODED:-}"; then {
        base64 -d <<< "${DISCORD_BOT_CONFIG_ENCODED}" > "${config_name}"
        cargo run -- "${config_name}"
      } else {
        printf '%s\n' \
          ">>> Please update/fill-up ./${config_name} with the necessary information and run:" \
          "" \
          $'\033[1;33m'"cargo run -- ${config_name}"$'\033[0m'
      } fi

  - name: Meilisearch
    command: |
      meilisearch --no-analytics --master-key "${MEILISEARCH_API_KEY}" --env development --http-addr 0.0.0.0:7700 --db-path ./data.ms

vscode:
  extensions:
    - matklad.rust-analyzer

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    # DANGER: do not enable!!
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
