# Example BotConfig
# Please fill it up with your own data
# Do not commit in git

[discord]
application_id = 12345678901234567890
bot_token = "QWERTYUIOP.ASDFGHJKL.123456789"

# optional
[discord.channels]
general_channel_id = 12345678901234567890
off_topic_channel_id = 12345678901234567890
introduction_channel_id = 12345678901234567890
getting_started_channel_id = 12345678901234567890
primary_questions_channel_id = 12345678901234567890
secondary_questions_channel_id = 12345678901234567890

# optional
[github]
api_token = "gh121345678"
user_agent = "optimusbot"

# optional
# This one does not need to be changed if you're debugging from Gitpod
[meilisearch]
api_key = "superCoolApiKey1234"
api_endpoint = "http://localhost:7700"
