[package]
name = "optimus"
version = "0.1.0"
authors = ["AXON <axonasif@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.91"
serde = { version = "1.0.152", features = ["derive"] }
regex = "1.7.0"
urlencoding = "2.1.2"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "sqlite", "offline"] }
meilisearch-sdk = "0.20.1"
words-count = "0.1.4"
html-escape = "0.2.13"
piston_rs = "0.4.3"
async-trait = "0.1.60"
duplicate = "0.4.1"
base64 = "0.20.0"
once_cell = "1.16.0"
color-eyre = "0.6.2"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-error = "0.2.0"

[dependencies.reqwest]
default-features = false
features = ["rustls-tls", "json"]
version = "0.11.13"

[dependencies.serenity]
path = "serenity/"
default-features = false
features = ["client", "unstable_discord_api", "gateway", "rustls_backend", "model", "utils", "cache", "framework", "standard_framework", "collector"]
#version = "0.10.10"

[dependencies.tokio]
version = "1.23.0"
features = ["macros", "rt-multi-thread", "process"]


[dependencies.anyhow]
version = "1.0.68"
features = ["backtrace"]
